name: Build docker image and run docfx
on:
  push:
    branches: [ main, feature/*, hotfix/* ]

jobs:
  docfx_docker_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      # Setup QEMU
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      #  with:
      #    platforms: linux/amd64,linux/arm64

      #- name: Set up Docker Buildx to enable custom build by Docker container build driver
      #  uses: docker/setup-buildx-action@v3
      #  with:
      #    platforms: linux/amd64,linux/arm64

      # Enable custom build by Docker container build driver
      #- name: Setup docker container
      #  run: |
      #    docker buildx create --name custom-builder --driver docker-container --platform linux/amd64,linux/arm64 --use --bootstrap
      #    docker buildx inspect --builder custom-builder
      #    docker buildx ls

      # Checkout
      - uses: actions/checkout@v4

      # Build docker image
      - run: >-
          docker build
          --tag sample
          ./
    
      # Output docker image size
      - run:
          docker images

      # Run docfx command
      - run: >-
          docker run
          --rm
          --volume ${{ github.workspace }}:/opt/prj

